### ISSUE TITLE
Add support of parquet files Encryption

### ISSUE THREAD

**Issue by maroil** [SETL-Framework/setl#179]
We need to allow developers to encrypt data in two ways:

- All data written by a connector
- Column level encryption using for example an annotation @Encrypt (with an option to select the right key)

Also, we have to provide an option that help developers read Encrypted data (even if they implement a key rotation policy)

Useful links:

[https://www.iteblog.com/sparksummit2018/efficient-spark-analytics-on-encrypted-data-with-gidon-gershinsky-iteblog.pdf](https://www.iteblog.com/sparksummit2018/efficient-spark-analytics-on-encrypted-data-with-gidon-gershinsky-iteblog.pdf)
[https://conferences.oreilly.com/strata/strata-ny-2019/cdn.oreillystatic.com/en/assets/1/event/300/Parquet%20modular%20encryption_%20Confidentiality%20and%20integrity%20of%20sensitive%20column%20data%20Presentation.pdf](https://conferences.oreilly.com/strata/strata-ny-2019/cdn.oreillystatic.com/en/assets/1/event/300/Parquet%20modular%20encryption_%20Confidentiality%20and%20integrity%20of%20sensitive%20column%20data%20Presentation.pdf)

**Comment by qxzzxq** [comment]
How is everything going? Do you have any suggestions on the design of this feature?
