### ISSUE TITLE
Add more error messages in compareDeliverables when require statement fails

### ISSUE THREAD

**Issue by LiuxyEric** [SETL-Framework/setl#184]
when require statement in `compareDeliverables` fails, it is possible to log `neededDeliverables` and `potentialDeliverables` ? 
it's hard to find out what are missing in `potentialDeliverables`

**Comment by qxzzxq** [comment]
Hey @LiuxyEric thanks for submitting the issue 😄 Can you please give us a more detailed description? For example, what are the current messages and what would you like to have?

I didn't work on this module, maybe @JorisTruong can you check this plz?

**Comment by JorisTruong** [comment]
Hi @LiuxyEric !

What version of SETL are you using?

As I mentioned in #176, the logs for the `deliverables` has been added on the current 1.0.0-SNAPSHOT version. I suggest you can try to use this version if you would like to find what `deliverables` are missing.

**Comment by LiuxyEric** [comment]
I've already solved the problem and it's because I used the delivery within same stage. thanks for your reply!
