### ISSUE TITLE
Throwing exception in com.fasterxml.jackson.core:jackson-databind call

### ISSUE THREAD

**Issue by tontolentino** [SETL-Framework/setl#196]
**Describe the bug**
When using SETL version 1.0.0-RC2 via SBT dependency builder by adding `libraryDependencies += "io.github.setl-framework" %% "setl" % "1.0.0-RC2"` into `build.sbt`, getting version 2.6.7.3 of `com.fasterxml.jackson.core:jackson-databind` which throws exception while building setl instance.
This behaviour can't be seen when using Maven builder (using `pom.xml`).

**To Reproduce**

1. Build project with SBT and add `libraryDependencies += "io.github.setl-framework" %% "setl" % "1.0.0-RC2"` to `build.sbt` file in project's root folder;
2. Check version of package `com.fasterxml.jackson.core:jackson-databind`. In my case, it was 2.6.7.3;
3. Run App.scala

**Expected behavior**
Correct creation of setl instance.

**Screenshots**
![image](https://user-images.githubusercontent.com/23459789/114952795-6fb85380-9e2d-11eb-928d-7e5b20c4f9c3.png)

**Environment (please complete the following information):**
 - OS: Windows 10
 - Dependencies:

**Additional context**
As a workaround, I've excluded the jackson-databind_2.6.7.3 dependency while importing setl-framework and added the correct version (jackson-databind_2.10.0):

`libraryDependencies ++= Seq(
  "io.github.setl-framework" %% "setl" % "1.0.0-RC2"
    exclude("com.fasterxml.jackson.core", "jackson-databind_2.6.7.3"),
  "com.fasterxml.jackson.core" % "jackson-databind" % "2.10.0"
)`

**Comment by qxzzxq** [comment]
thanks @tontolentino for this issue. We will look into it 👍

**Comment by qxzzxq** [comment]
What is your spark and scala version? Do you have other dependencies that depend on `com.fasterxml.jackson.core:jackson-databind`?

**Comment by tontolentino** [comment]
Spark: 3.0.1
Scala: 2.12.10

No other dependecy on `com.fasterxml.jackson.core:jackson-databind`

**Comment by qxzzxq** [comment]
@tontolentino This issue comes from a library used in SETL framework. We will try to solve it. 

Normally the lib `jackson-databind_2.6.7.3` should be overwritten by version 2.10.0 when Spark is added into the sbt build file:

![Screenshot 2021-06-28 at 09 11 37](https://user-images.githubusercontent.com/17144939/123566028-433b9300-d7f1-11eb-86cf-d5ab9b4d56b2.png)

my build.sbt:
```scala
name := "issue_196"

version := "0.1"

scalaVersion := "2.12.10"

idePackagePrefix := Some("com.example")

libraryDependencies += "org.apache.spark" %% "spark-core" % "3.0.0"
libraryDependencies += "io.github.setl-framework" %% "setl" % "1.0.0-RC2"
```
