### ISSUE TITLE
Broken links in index.md

### ISSUE THREAD

**Issue by R7L208** [SETL-Framework/setl#210]
**Describe the bug**
Links for PipelineInspector, PipelineOptimizer, and DeliverableDispatcher are broken in documentation

**To Reproduce**

- https://setl-framework.github.io/setl/PipelineInspector
- https://setl-framework.github.io/setl/PipelineOptimizer
- https://setl-framework.github.io/setl/DeliverableDispatcher

**Expected behavior**
Links should be removed from docs or fixed

**Additional context**
No markdown files for these in `setl/tree/master/docs`

**Comment by qxzzxq** [comment]
Thanks for submitting the issue. These docs are not done yet :p I'll add them asap.
