### ISSUE TITLE
failed to setJobGroup

### ISSUE THREAD

**Issue by conderls** [SETL-Framework/setl#228]
**Describe the bug**
```scala
val factory = new SomeFactory()
factory.setJobGroup("new-group-name", "description")
pipeline.addStage(factory)
```
the JobGroup in the spark UI does not update.

**Expected behavior**
![image](https://user-images.githubusercontent.com/6688515/148332409-69d9aef0-147c-437e-9bc3-a77d68d5328f.png)
`JobGroup` and `Description` should be "new-group-name" and "description" respectively.

**Environment (please complete the following information):**
- spark: 2.4.3
- SETL: 1.0.0_RC1

**Comment by qxzzxq** [comment]
Hi @conderls thank you for your feedback. Indeed this is an issue. Currently your changes made by the call of `setJobGroup` will be overwritten when the stage is running ([line 227 in workflow/Stage.scala](https://github.com/SETL-Framework/setl/blob/c96fa32392599c76313edb5bb9eece9d8d8518cd/src/main/scala/io/github/setl/workflow/Stage.scala#L227)).

A temporary workaround could be to call `setJobGroup` in the `read()` method of your factory. However, the limitation is that you may not be able to modify the job description.

We will fix this problem in the next release.
